### ISSUE TITLE
"files" seems to be ignored

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3-Continuous-Integration/TYPO3-CI-Xliff-Lint#2]
With 

```yaml
- uses: typo3-continuous-integration/typo3-ci-xliff-lint@v1
  with:
    files: './packages/'
```

the constraint for the directory is not taken into account - I get results from `./var/labels` as well.

I think that the input parameters need to be declared in `actions.yaml`: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs

You'll get it as `$1` then in your Docker entrypoint: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#writing-the-action-code
